### PR TITLE
FIX: Dark mode UI Contrast

### LINKED ISSUE #57: docs: Misalignment
Misalignment previous & next page:

image

### LINKED ISSUE #164: [Bug]: Poor contrast in UI when using dark mode
**Describe the bug**
While browsing through the documentation I've noticed that some elements are either hard to read or unreadable at all when using dark mode due to lack of contrast.

**To Reproduce**

Go to the urls to see the corresponding element that lacks contrast.

*I've used a [contrast checker](https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=1F2937) to test the contrast:*

| URL | Light Mode ✅ | Dark Mode ❌ | Contrast Result *(dark mode)* |  
|---|---|---|---|
| https://docs.devprotocol.xyz/en/ | image | image  | image |
| https://docs.devprotocol.xyz/en/ | image | image | image |
| https://docs.devprotocol.xyz/en/introduction/ | image | image | image |
| https://docs.devprotocol.xyz/en/introduction/devtoken/ | image | image | image |
| https://docs.devprotocol.xyz/en/introduction/creatortoken/ | image | image | image |
| https://docs.devprotocol.xyz/en/whitepaper/ | image | image | image
| https://docs.devprotocol.xyz/en/stakes-social/ | image | image | image
| https://docs.devprotocol.xyz/en/developers/modules/dev/ | image | image | image
| https://docs.devprotocol.xyz/en/learning/learning/display-properties-perform-staking/ | image | image | image

**Expected behavior**
The UI should be easy to read and pass the contrast checker when using dark mode.

### PR DESCRIPTION
**Pull request by Simperfy**
- Fixed misaligned navigation links when content is empty.
- Fixed multiple contrast problem in dark mode:

| Before ❌ | After ✅ | Contrast Result *(dark mode)* |
|---|---|---|
| image | image | image
| image | image | image
| image | image | image
| image | image | image |
| image | image | image |
| image | image | image |
| image | image | image |
| image | image | image |
| image | image | image |

- Fixes #57
- Fixes #164

### CODE REVIEW

**Comment by Simperfy** [comment]
How do I resolve this error in tests?
image

**Comment by vinzvinci** [comment]
> How do I resolve this error in tests? _I think this is a permission error related to the automated tests and not from the changes I made._
> 
> image

I think we can merge this @aggre?

**Comment by KukretiShubham** [comment]
image
Will this region be light mode, even in the dark theme?

**Comment by Simperfy** [comment]
> image Will this region be light mode, even in the dark theme?

Yes. Do you want me to invert this image color *(in dark theme)* instead?

**Comment by vinzvinci** [comment]
Hi Simperfy, thanks for your contributions. Sorry, this was delayed because we navigate to new docs (docusaurus), will close this issue now. Feel free to contribute if u found something.

**Comment by Simperfy** [comment]
> Hi Simperfy, thanks for your contributions. Sorry, this was delayed because we navigate to new docs (docusaurus), will close this issue now. Feel free to contribute if u found something and chat the pr or issues link on docs channel,

It's okay, no problem.

**Pull request closed without merging**
