### PR TITLE
Adds i18n and translate the doc to Portuguese

### PR DESCRIPTION
**Pull request by rafaelp**
Didn't know exactly how 404 not found is handle. I suppose it is handled by Netlify, that's why I didn't put the code to render 404 that I found on Initto.
I didn't change the Netlify admin configuration, because I don't have access to it.

### CODE REVIEW

**Comment by kazu80** [comment]
Thanks @rafaelp 
That means is redirect old URL to new URL ?

"http://localhost:8080/stakes-social/" to "http://localhost:8080/en/stakes-social/"

I definitely want to solve this problem. Isn't it possible to deal with it like initto?
By the way, We use Vercel for the hosting service.

**Comment by kazu80** [comment]
One more request.

Stakes_Social

**Comment by kazu80** [comment]
Avatar t 01

**Comment by rafaelp** [comment]
@kazu80 This code to the job of redirecting quite the same way I did on innito:
https://github.com/dev-protocol/docs.devprotocol.xyz/pull/51/files#diff-6f7ee17dfb4e34cde9f7ffa0b8306d391edabccb5ace4e12d098ddb8d291336dR60

**Comment by rafaelp** [comment]
> One more request.
> 
> Stakes_Social

Done.

**Comment by kazu80** [comment]
Thanks @rafaelp 
Can the logo image be made smaller?

スクリーンショット 2021-07-26 12 56 40

**Comment by rafaelp** [comment]
> Thanks @rafaelp
> Can the logo image be made smaller?
> 
> スクリーンショット 2021-07-26 12 56 40

Humm.. very strange, it was off course. I will take a look

**Comment by rafaelp** [comment]
@kazu80  The CSS somehow was not committed.
Well, it should be like
Screen Shot 2021-07-27 at 13 04 57

**Comment by rafaelp** [comment]
@kazu80 I've rebased from main and squashed last commits and now the PR is good to merge

**Pull request merged**
