### PR TITLE
feat: Convert all issue templates into issue forms

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Convert all issue templates into issue forms.

### CODE REVIEW

**Comment by vinzvinci** [comment]
Closed this PR, already merged on .github repo.

**Comment by Panquesito7** [comment]
> Closed this PR, already merged on .github repo.

Yes, but it doesn't make an effect if there are issue templates in this repository. The `.github` ones are just fallbacks.

**Comment by vinzvinci** [comment]
Hmm I see. If the issue templates here is outdated, just tell me and I'll reopen this issue and assign it to you?

**Comment by Panquesito7** [comment]
> Hmm I see. If the issue templates here is outdated, just tell me and I'll reopen this issue and assign it to you?

It'd be great if you can re-open this and merge it (it's a PR by the way). Thanks. 😄

**Comment by vinzvinci** [comment]
Cool. Open now

**Review by vinzvinci — CHANGES_REQUESTED** [review]
Please update this PR, same with https://github.com/dev-protocol/.github/tree/main/.github/ISSUE_TEMPLATE

**Review by vinzvinci — APPROVED** [review]
LGTM, I decided to change the bug same with the issue template on .github

**Pull request merged**
