### PR TITLE
Add modules

### PR DESCRIPTION
**Pull request by 0xkenta**
Please check Allocator, Lockup, and Withdraw under content/en/pages/3000-developers/modules.

### CODE REVIEW

**Comment by vinzvinci** [comment]
So many conflicting files. Is this will continue?

**Comment by 0xkenta** [comment]
> So many conflicting files. Is this will continue?

I made PR 2 months ago and since then I saw many changes on a new page. I don't know if they will be needed or not.

**Comment by vinzvinci** [comment]
Okay if there's still changes needed, feel free to ping me and I can update it for you

**Comment by 0xkenta** [comment]
OK thanks.

**Pull request closed without merging**
