### PR TITLE
Fix title and paging to match navigation

### PR DESCRIPTION
**Pull request by osaguild**
### description
- "docs.devprotocol.xyz" title and paging is not matched navigation and some navigation title is not simple
- I fixed the title and paging to be more actuate and simpler

### fixed lists
| directory| fixed point |
|--|--|
|00-Introduction| fixed title |
|0000-protocol| fixed order number 3x to 1xx and some paging dees not work|
|2000-stakes-social| fixed order number 2xxx to 20xx|
|2500-niwa| fixed title to match navigation|
|3000-developers| fixed order number and some paging dees not work|
|4000-learning| fixed title to match navigation and simplified long title|

### attention
- Fixed only en version (not ja and pt)
- If this pr is ok, I will fix the other lang versions (maybe I need help to fix po...)

### CODE REVIEW

**Review by vinzvinci — COMMENTED** [review]
Looks good, but need confirmation about the title changes with the team if they agree or have suggestions on what to change.

**Comment by osaguild** [comment]
Hi @vinzvinci, thanks for the comment. Do you mean I need to suggest in [dev protocol forum](https://community.devprotocol.xyz/)?

**Comment by vinzvinci** [comment]
No, just wait for the other feedback here. CC @KukretiShubham @yumemayu

**Comment by aggre** [comment]
LGTM!

**Review by vinzvinci — APPROVED** [review]
Okay cool, merging this!

**Pull request merged**
