### PR TITLE
Published Onboard guide for Polygon

### PR DESCRIPTION
**Pull request by vinzvinci**

### CODE REVIEW

**Review by KukretiShubham — COMMENTED** [review]
Is this an old ss? here I don't see polygon in SS

**Comment by vinzvinci** [comment]
> Is this an old ss? here I don't see polygon in SS

Hmm there is

P. provided these images

**Comment by vinzvinci** [comment]
Updated

**Review by KukretiShubham — APPROVED** [review]
LGTM

**Pull request merged**
