### PR TITLE
added: Dev Interface remix-ready file + solidity highlighter

### PR DESCRIPTION
**Pull request by KukretiShubham**

### CODE REVIEW

**Review by aggre — CHANGES_REQUESTED** [review]
DevInerface.sol you wrote is for V1, so you need to use the mainnet address.

Dev.deposit,depositFrom are legacy interfaces for backward compatibility that exist only in mainnet and do not exist in Polygon/Arbitrum.

**Comment by KukretiShubham** [comment]
> DevInerface.sol you wrote is for V1, so you need to use the mainnet address.
> 
> Dev.deposit,depositFrom are legacy interfaces for backward compatibility that exist only in mainnet and do not exist in Polygon/Arbitrum.

Sure, i will fix this. Anyway there are some interfaces missing here https://github.com/dev-protocol/protocol/blob/main/contracts/interface/IDev.sol . 
Shall I add here ?

**Comment by aggre** [comment]
No need to add them. Because they're legacy interfaces, and sTokens ver. staking doesn't used them.

**Review by vinzvinci — COMMENTED** [review]
Pinging @aggre for final review

**Review by aggre — APPROVED** [review]

**Pull request merged**
